name: Production Deploy to HF
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger HF Factory Reboot
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $HF_TOKEN" \
          "https://huggingface.co/api/spaces/hansaka1/alexa/restart?factory=true"